# Generated by Django 3.2.5 on 2021-08-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_like_like_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_id',
        ),
        migrations.AddField(
            model_name='product',
            name='like_id',
            field=models.IntegerField(default=0),
        ),
    ]
