# Generated by Django 3.2.5 on 2021-08-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
