# Generated by Django 3.2.5 on 2021-08-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='like_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
