# Generated by Django 3.2.5 on 2021-08-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
    ]
